### PR TITLE
refactoring data-mgt microservice 

### PR DESCRIPTION
**Pull request by Baalmart**
# Chore

**_WHAT DOES THIS PR DO?_**
refactoring data-mgt microservice to ensure that it can cater for more pipeline work in many different languages/frameworks

### CODE REVIEW

**Review by ONENEMMANUEL — APPROVED** [review]
Looks good

**Comment by michaelgobz** [comment]
wait thought there is gona be code in those files

**Comment by michaelgobz** [comment]
if that is true then am also good

**Review by michaelgobz — COMMENTED** [review]
though i expected may be code to be in those files

**Pull request merged**
